### PR TITLE
Docs: Fixed quick start expected output format error

### PR DESCRIPTION
**Pull request by wangeguo**
### Description of your changes

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] Update `sidebar.js` if adding a new page.
- [ ] Run `yarn start` to ensure the changes has taken effect.

### CODE REVIEW

**Comment by wonderflow** [comment]
what format error?

**Comment by wangeguo** [comment]
> what format error?

截屏2023-01-12 13 47 26

**Review by wonderflow — APPROVED** [review]
good catch! please sign the DCO

**Comment by wangeguo** [comment]
@wonderflow All commits are signed off!

**Pull request merged**
