### PR TITLE
Feat: add sitemap for kubevela

### LINKED ISSUE #976: configure sitemap plugin
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap

> Minor web buglet report : I've noticed that if I search google for e.g. "kubevela docs webservice" and choose the top hit, I'm taken to docs for v1.0 with a banner saying "click here for latest version".  Would a sitemap update correct this to go directly to latest docs?

### PR DESCRIPTION
**Pull request by wonderflow**
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

### Description of your changes

Fixes #976

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] Update `sidebar.js` if adding a new page.
- [ ] Run `yarn start` to ensure the changes has taken effect.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by wonderflow** [comment]
@Arhell Do you know why CI fails? I don't find the duplicate one.

**Comment by Arhell** [comment]
> @Arhell Do you know why CI fails? I don't find the duplicate one.

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap

**If you use the preset @docusaurus/preset-classic, you don't need to install this plugin as a dependency.**

https://github.com/kubevela/kubevela.io/blob/main/package.json#L22

**Comment by Arhell** [comment]
I think we need to remove this dependency and leave the options

**Review by barnettZQG — APPROVED** [review]

**Pull request merged**
