### PR TITLE
Fix: velad install script

### PR DESCRIPTION
**Pull request by chivalryq**

### CODE REVIEW

**Review by barnettZQG — APPROVED** [review]

**Review by wonderflow — APPROVED** [review]

**Comment by BartNetJS** [comment]
I still had to install a gzip tool (like cygwin) and added it the environment variables as explained here https://stackoverflow.com/questions/36733176/how-do-i-add-a-gzip-command-to-windows-cmd
to get it up and running

**Comment by wonderflow** [comment]
@BartNetJS Do you mean just install it by downloading a binary in `.exe`  format?

**Comment by BartNetJS** [comment]
I downloaded the setup exe.
These were the steps I took:
Step 1: Download and install [Cygwin](https://www.cygwin.com/)

Step 2: Click 'Start' and type System Environment Variables
Step 3: In the 'Advanced' tab, click 'Environment Variables...'
Step 4: In the 'User variables for (user)' section, select the Path variable and click 'Edit...'
Step 5: In the 'Edit environment variable' window, click 'New'
Step 6:
For x86 type: C:\cygwin\bin
For x64 type: C:\cygwin64\bin
Step 7: Restart CMD, type gzip, and shout, "Wooooo!"

as mentioned here https://stackoverflow.com/questions/36733176/how-do-i-add-a-gzip-command-to-windows-cmd

**Comment by charlie0129** [comment]
> I downloaded the setup exe. These were the steps I took: Step 1: Download and install [Cygwin](https://www.cygwin.com/)
> ...

Thank you for the detailed steps. We need to improve this and make the installation easier. These are the steps you shouldn't have taken.

Possibly cause by: https://github.com/kubevela/kubevela/issues/4542#issuecomment-1202792941

**Pull request merged**
