### PR TITLE
Fix: the install scripts now picks the latest version and binary from…

### LINKED ISSUE #1254: Fix the vela cli install script to pick the latest version from github
Currently when we try to run the vela cli install script from the document, it seems to be pointing to the latest version as 1.8 version of the cli while the currently released version is 1.9.4. 

Expected behavior
We expect that the script looks up github and finds the latest release from there

KubeVela Version

1.9.4

Additional context
Having the script look up the version as well as the binary using github apis to download and install would be more future proof.

### PR DESCRIPTION
**Pull request by anoop2811**
… github (kubevela#1254)

- also fixed the kubectl-vela install script

### Description of your changes

Fixes #1254 : Update the script to pick the latest version from github 

I have:

- [x ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ x] Update `sidebar.js` if adding a new page.
- [ x] Run `yarn start` to ensure the changes has taken effect.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
Thanks! We also need to update the documentation in the installation page.

**Comment by anoop2811** [comment]
> Thanks! We also need to update the documentation in the installation page.

Yes, I was hoping to get the script in and then use the github raw file url in the doc. Or I could extrapolate the path and update this commit. @wonderflow : WDYT?

**Comment by wonderflow** [comment]
> 

Sure, we can merge this pull request frist after the CI checks passed. Then we can verify the installation script before update the documentation.

**Comment by anoop2811** [comment]
@wonderflow : I went ahead and updated the links to use kubevela.io for the scripts as well.

**Pull request merged**
