### PR TITLE
Add Chart configuration list

### PR DESCRIPTION
**Pull request by zzxwill**
List all Chart configuration parameters (values which could be overridden)
when install kubeVela chart

### CODE REVIEW

**Comment by zzxwill** [comment]
I will add the Chinese version after involving related developers.

**Review by Somefive — APPROVED** [review]

**Review by wonderflow — CHANGES_REQUESTED** [review]
replicated with https://kubevela.io/zh/docs/platform-engineers/system-operation/bootstrap-parameters

**Review by Somefive — CHANGES_REQUESTED** [review]
It looks a bit messy to place the introduction of helm parameters here.

**Comment by zzxwill** [comment]
> replicated with https://kubevela.io/zh/docs/platform-engineers/system-operation/bootstrap-parameters

不一样，这写是不能暴露出来的，这些代码层级的参数 end-users 和 paltform-builder 都没有能力去做变更，我跟@somefive 对一下，把他们转成 chart 可以自定义的参数暴露给 platform builder.

**Pull request closed without merging**
