### PR TITLE
dingding-notification message error

### PR DESCRIPTION
**Pull request by yueyongyue**
### Description of your changes

dingding-notification message error

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] Update `sidebar.js` if adding a new page.
- [ ] Run `yarn start` to ensure the changes has taken effect.

### Special notes for your reviewer

@wonderflow

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
Great. Please sign the dco

**Comment by yueyongyue** [comment]
@wonderflow DCO checked

**Review by FogDong — APPROVED** [review]

**Comment by FogDong** [comment]
@yueyongyue  Hi, this doc is generated by the code in https://github.com/kubevela/kubevela/blob/master/references/docgen/def-doc/workflowstep/notification.eg.md ,
please also help to fix the example, thanks for the contribution!

**Comment by yueyongyue** [comment]
@FogDong https://github.com/kubevela/kubevela/pull/5424

**Pull request merged**
