### PR TITLE
Docs: add LFX mentorship blog post.

### PR DESCRIPTION
**Pull request by iyear**
### Description of your changes

Part of https://github.com/kubevela/kubevela/issues/5364

Preview:
<details><summary>Details</summary>

en
zh

</details> 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] Update `sidebar.js` if adding a new page.
- [x] Run `yarn start` to ensure the changes has taken effect.

### Special notes for your reviewer

The English version is based on the ChatGPT translation and has been manually proofread.

Feel free to review.

### CODE REVIEW

**Review by Somefive — APPROVED** [review]
Great job!

**Review by Somefive — COMMENTED** [review]
The image link path is suggest to use relative path.

**Comment by iyear** [comment]
I see workflow-chatgpt post use `The logs of diagnose step` to display image. Can you give an example that how to use relative path?

**Comment by Somefive** [comment]
> I see workflow-chatgpt post use `The logs of diagnose step` to display image. Can you give an example that how to use relative path?

You can try ../static/img/blog/lfx-cue/generator/xxx for English doc but that will require you to add these images to the Chinese folder as well. I think it is ok to use absolute path now since the documentation site is placed at the root path.

**Pull request merged**
