### PR TITLE
add column 'verified' to cloud-resources-list.md

### PR DESCRIPTION
**Pull request by AveryQi115**
Signed-off-by: Nicola115 <2225992901@qq.com>

### CODE REVIEW

**Review by zzxwill — APPROVED** [review]
Good job!

**Review by wonderflow — COMMENTED** [review]
please add sort for docs

**Comment by Nicola115** [comment]
I've add sort for docs. But it's strange in Chinese version docs. As the provider names both include Chinese and English, like 'AWS' and '阿里云'.

**Comment by AveryQi115** [comment]
> please add sort for docs

I've add sort for docs. But it's strange in Chinese version docs. As the provider names both include Chinese and English, like 'AWS' and '阿里云'.

**Comment by wonderflow** [comment]
@Nicola115 Will it cause the same big change as the random order when we update next time?

**Comment by AveryQi115** [comment]
> @Nicola115 Will it cause the same big change as the random order when we update next time?

Yes, you need to sort it after updates if you want to remain the alphabetical order. I've write a tool for sorting docs, and @zzxwill raise an issue for it. https://github.com/oam-dev/kubevela/issues/3536 Guess we might include the sorting in kubevela soon.

**Pull request merged**
