### PR TITLE
Add a tutorial on how to provision a database with sql file imported

### PR DESCRIPTION
**Pull request by zzxwill**
Add a turotial to introduct how to provision a relational database with
SQL file imported, and bootstrap an application which depends on the database.

Signed-off-by: Zheng Xi Zhou <zzxwill@gmail.com>

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
please make the picture smaller

**Comment by zzxwill** [comment]
> please make the picture smaller

Done, thanks for the suggestion.

**Review by wonderflow — COMMENTED** [review]
please finish the translation

**Comment by zzxwill** [comment]
> please finish the translation

Done.

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
