### PR TITLE
Update triggers list

### PR DESCRIPTION
**Pull request by tossmilestone**
Add missing triggers

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

**Review by barnettZQG — APPROVED** [review]

**Comment by barnettZQG** [comment]
@tossmilestone Please synchronous change the chinses doc.  https://github.com/oam-dev/kubevela.io/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/how-to/dashboard/trigger/overview.md

and update 1.2 version:
```
make update-version version=v1.2 
```

**Comment by tossmilestone** [comment]
@barnettZQG OK

**Comment by tossmilestone** [comment]
@barnettZQG done, PTAL

**Comment by barnettZQG** [comment]
> @barnettZQG done, PTAL

Good job, thanks!

**Pull request merged**
