### PR TITLE
Nikhil/linkfix

### PR DESCRIPTION
**Pull request by nikhilchauhangithub**
### Description of your changes

fix the standalone and Kubernetes hyperlink on the page https://kubevela.io/docs/install
"Fixes #6238":

I have:

- [ x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x ] Update `sidebar.js` if adding a new page.
- [x ] Run `yarn start` to ensure the changes has taken effect.

-->

### CODE REVIEW

**Comment by wonderflow** [comment]
Hi  @Arhell , do you know how to reduce the changes in yarn.lock?

**Review by Arhell — COMMENTED** [review]
This PR does not need to update dependencies, there is another one for this https://github.com/kubevela/kubevela.github.io/pull/1261

I personally use this https://www.npmjs.com/package/npm-check-updates

**Comment by chivalryq** [comment]
Both links here works well in Edge:

image

And I tried several times, found if I open https://kubevela.io/docs/install/ directly and the link is broken. However, if I go to this page by 

1. Open https://kubevela.io/docs/
2. Click `Installation`

Then it works well. Do you have any ideas about this @Arhell? Before it is clear we should pend this PR.

**Comment by chivalryq** [comment]
Related: https://github.com/kubevela/kubevela.github.io/issues/1268 Closing this PR because this is not the root problem.

**Pull request closed without merging**
